### ISSUE TITLE
Cursive compatability on Windows 11

### ISSUE THREAD

**Issue by LimesKey** [genieCS/retris#111]
I just saw your Reddit post and wanted to try it out but I had some issues with the Cursive crate, I got this error, `error: failed to run custom build command for ncurses v5.101.0`. I ended up doing some research and found that ncurses isn't compatible with Windows. I saw some post online to change the backend to the pancursive backend with this line, `cursive = { version = "0.20", default-features = false, features = ["pancurses-backend"] }` and it worked! 

The game was great but I experienced one more issue, the last block pixel was cut off. I tried manually re-adjusting the window but it didn't help. 
![image](https://github.com/genieCS/retris/assets/85136735/69f86fb0-1c8d-4369-af14-3f5d6c38866c)
Did you only test this on Linux?

**Comment by genieCS** [comment]
@LimesKey 
👋🏻Thank you for bringing the issue.
I appreciate your interest in my project💛
I tested in OS X and Linux and didn't know the issue. I'll check it.
for backend, I'll change it in #39 and let you know:)

**Comment by genieCS** [comment]
@LimesKey I added backend configuration in #112 and will keep you posted on window problem

**Comment by LimesKey** [comment]
Has it been fixed?

**Comment by LimesKey** [comment]
Sorry for late reply @genieCS, seems to work perfectly now! It compiled correctly and without errors. I ran it both with Powershell and Command Prompt and both work great, you fixed the few pixel cut-off issue!

**Comment by genieCS** [comment]
@LimesKey awesome. thank you for check and enjoy retris:)
